
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: msa-weather-config-client
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/
auther: Aaryn 